const OPTIONS_NAME = {
  OPTION0: "clock",
  OPTION1: "pendulum",
  OPTION2: "tree",
  OPTION3: "cup",
  OPTION4: "saltAndPepper",
  OPTION5: "headphones",
  OPTION6: "vacum",
  OPTION7: "globe",
  OPTION8: "fan",
  OPTION9: "moon",
  OPTION10: "belt",
  OPTION11: "wallet",
  OPTION12: "officeLamp",
  OPTION13: "plantPot",
  OPTION14: "candle",
};
const OPTIONS = {
  OPTION0: `/assets/${OPTIONS_NAME.OPTION0}.png`,
  OPTION1: `/assets/${OPTIONS_NAME.OPTION1}.png`,
  OPTION2: `/assets/${OPTIONS_NAME.OPTION2}.png`,
  OPTION3: `/assets/${OPTIONS_NAME.OPTION3}.png`,
  OPTION4: `/assets/${OPTIONS_NAME.OPTION4}.png`,
  OPTION5: `/assets/${OPTIONS_NAME.OPTION5}.png`,
  OPTION6: `/assets/${OPTIONS_NAME.OPTION6}.png`,
  OPTION7: `/assets/${OPTIONS_NAME.OPTION7}.png`,
  OPTION8: `/assets/${OPTIONS_NAME.OPTION8}.png`,
  OPTION9: `/assets/${OPTIONS_NAME.OPTION9}.png`,
  OPTION10: `/assets/${OPTIONS_NAME.OPTION10}.png`,
  OPTION11: `/assets/${OPTIONS_NAME.OPTION11}.png`,
  OPTION12: `/assets/${OPTIONS_NAME.OPTION12}.png`,
  OPTION13: `/assets/${OPTIONS_NAME.OPTION13}.png`,
  OPTION14: `/assets/${OPTIONS_NAME.OPTION14}.png`,
};

export { OPTIONS, OPTIONS_NAME };
